site_name: Conia Sire
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: conia
repo_url: https://github.com/coniadev/sire
extra:
    project: Sire
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition
